apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: carousel
  description: The VTEX Carousel app is a store component that shows a collection
    of banners, and this app is used by store theme.
  tags:
    - typescript
    - react:16
  annotations:
    vtex.com/janus-acronym: ""
    vtex.com/o11y-os-index: ""
    grafana/dashboard-selector: ""
    github.com/project-slug: vtex-apps/carousel
    vtex.com/platform-flow-id: Shopper#1,Merch#8
    backstage.io/techdocs-ref: dir:../
    vtex.com/application-id: 2BZBV7DM
spec:
  system: store-framework-ui-apps
  lifecycle: stable
  owner: te-0013
  type: frontend-ui
  dependsOn: []
  subcomponentOf: store-framework
